### PR TITLE
Add Italian

### PR DESCRIPTION
**Pull request by AndyDL24**
Hello I finished the translation of the quests, many machineries are in original language, I thought that the game is started in English so only the explanations of the quests I have physically translated. Thanks for your patience.

### CODE REVIEW

**Comment by CuboidDroid** [comment]
Thanks for this. I'm currently working on the multi-lingual support. I'll be pushing up changes after a little bit of testing. The new language file will be JSON. Hopefully you'll be happy to give it a quick review once it's up there (I think there were a few quests that are still English) and will be able to create a PR for the last few changes. It's looking great so far though! :)

**Comment by AndyDL24** [comment]
Hello, yes I have checked and in fact some parts I have not translated thank you I will fix as soon as possible, for the JSON file there are no problems as soon as you have completed the implementation of the files I will check again. Thank you.

**Comment by AndyDL24** [comment]
Hi, I added the strings that were missing.  I noticed something today while I was playing it, the first part of the quests, basically the gettin start, doesn't show me the links between the quests, do you know why?  the IDs maybe?  however you find everything in my github

**Comment by CuboidDroid** [comment]
Thanks for this. I've now introduced multi-lingual support. The quest text is now found in src/overrides/kubejs/assets/cuboidquests/lang with English in en_us.json and your Italian translations in it_it.json - your changes should be included in there. Before I release the pack with this in, it would be helpful if you could cast your eye over it and check if there are any last-minute changes needed.

Also, please let me know what you would like me to say when thanking you for the translation? At the moment the change log says: 

Added Italian quest text translations - thanks to AndyDL24!

Thanks again!

**Comment by AndyDL24** [comment]
Hi, the only updates I've found I've already modified, the only thing I can't figure out if it depends on the IDs because the first part doesn't show me the links between quests. If you confirm that it resolves itself during the installation you can also post the updates. For the name you can put AndyD. Thank you very much.

**Comment by CuboidDroid** [comment]
Ok great. I'll hopefully get out the update in the next day or two.

**Comment by CuboidDroid** [comment]
I have released 1.1.2 which includes the Italian quest text if you'd like to see it in action :)

**Comment by AndyDL24** [comment]
Hello, yes it works the Italian language of the quests but only if you put all Minecraft in Italian, I thought you added a button to put only the quests created by you in Italian, because I left many things in English to facilitate the search in JEI and as we know many mods are not in Italian. Anyway it's beautiful it works great you've been great. Thank you.

**Comment by CuboidDroid** [comment]
Thanks again!

**Pull request closed without merging**
